---
title: "GOenriched_dotplot.RmD"
output: html_document
date: '2023-07-13'
author: 'Elias Rafael Ruiz-Morales'
Institution: 'Wellcome Sanger institute'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Code to plot the GO dotplot of shared upregulated pathways accross all infections and cell lineages.  

```{r}
library(GOplot)
library(ggplot2)
library(scales)
library(dplyr)
```


GO enriched in up-regulated genes
```{r}
HBC = read.csv("../diffGeneExpression/macrophages/dotplotGO_shared_HBC.csv", header=T)
PAMM1 = read.csv("../diffGeneExpression/macrophages/dotplotGO_shared_PAMM1.csv", header=T)
VCT = read.csv("../diffGeneExpression/trophoblast/dotplotGO_shared_VCT.csv", header=T)
VCTf = read.csv("../diffGeneExpression/trophoblast/dotplotGO_shared_VCTf.csv", header=T)

Endo = read.csv("../diffGeneExpression/fibroEndo/dotplotGO_shared_Endo.csv", header=T)
PV = read.csv("../diffGeneExpression/fibroEndo/dotplotGO_shared_PV.csv", header=T)
Fibro = read.csv("../diffGeneExpression/fibroEndo/dotplotGO_shared_F.csv", header=T)


infections_Go<- rbind(HBC,PAMM1,VCT,VCTf,Endo,PV,Fibro)
```





## Figure 2: Shared dotplot for all cell compartments -- GO enriched

```{r}

#'GO:0001525-angiogenesis',
#setting order of the GOs for ploting
desired_order<- c( 'GO:0001525-angiogenesis',  'GO:0045766-positive regulation of angiogenesis', 'GO:0045765-regulation of angiogenesis')

#subset only the desired categories:

infections_Go_subset<- infections_Go[infections_Go$GeneOntology %in% desired_order, ]


#infections_Go_subset$negLogP <- ifelse(infections_Go_subset$negLogP > 20, 20, infections_Go_subset$negLogP)



# Some cell types might not have any of the categories enriched, giving an empty column in the dotpplot.
# This line created a value of 0 enrichment for those celltypes to have a complete plot
new_row <- data.frame(GO='GO:0001525', LogP = 0, Enrichment=0, Description= 'angiogenesis', Infection='Lm_VCTf' , GeneOntology='GO:0001525-angiogenesis', negLogP=0 )
infections_Go_subset <- rbind(infections_Go_subset, new_row)

new_row <- data.frame(GO='GO:0001525', LogP = 0, Enrichment=0, Description= 'angiogenesis', Infection='Tg_VCTf' , GeneOntology='GO:0001525-angiogenesis', negLogP=0 )
infections_Go_subset <- rbind(infections_Go_subset, new_row)




# plot: dot plot
ggplot(data = infections_Go_subset, aes(x = Infection, y = GeneOntology, color = negLogP, size = Enrichment)) + 
  geom_point() +
  #scale_color_gradient2(low ='#e8fa5bff' , high = "#13306dff", mid = "#de7065ff",  limits = c(0, 20))+
  #scale_color_gradientn(colours = viridis::plasma(9))+

  scale_color_gradient(low ='gray', high = 'red')+
  #scale_fill_gradientn(colours = viridis::magma(9))+
  scale_size_continuous(breaks = c(4, 8, 12), range = c(2, 10)) +  # Set specific sizes to be shown, set the size range to be use
  theme_bw() + 
  ylab("") + 
  xlab("") + 
  #theme_classic()+ 
  theme(text=element_text(size=10), axis.text=element_text(size=10), axis.text.x=element_text(size=10,angle = 45, hjust = 1) ) +
  labs(color = "-Log10(p-val)") 
 
ggsave("./dotplotGO_sharedGOenriched_All.pdf",  width = 11, height =3)



```





```{r}

sessionInfo()

```

<!--
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: OS X  14.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.10       scales_1.2.1       GOplot_1.0.2       gridExtra_2.3      ggdendro_0.1.23   
[6] svglite_2.1.0      ggplot2_3.4.2      pheatmap_1.0.12    RColorBrewer_1.1-3

loaded via a namespace (and not attached):
 [1] pillar_1.8.1      compiler_4.0.2    tools_4.0.2       digest_0.6.28     evaluate_0.14    
 [6] lifecycle_1.0.3   tibble_3.1.8      gtable_0.3.1      pkgconfig_2.0.3   rlang_1.1.1      
[11] cli_3.4.0         rstudioapi_0.15.0 yaml_2.2.1        xfun_0.26         fastmap_1.1.0    
[16] withr_2.5.0       knitr_1.36        generics_0.1.3    vctrs_0.6.3       systemfonts_1.0.4
[21] grid_4.0.2        tidyselect_1.1.2  glue_1.4.2        R6_2.5.1          fansi_1.0.3      
[26] rmarkdown_2.11    farver_2.1.1      purrr_0.3.4       magrittr_2.0.1    htmltools_0.5.2  
[31] MASS_7.3-51.6     colorspace_2.0-3  labeling_0.4.2    utf8_1.2.2        munsell_0.5.0 

-->
